import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Projects from '../components/Projects'
import Skills from '../components/Skills'
import WorkExperience from '../components/WorkExperience'
import styles from '../styles/Home.module.css'

{/**
  - https://www.youtube.com/watch?v=urgi2iz9P6U&list=PLsM7KdGtJeEf6JKnNs7I4ARIS65OO46M3&index=7
  - 1:54:37
  - lemon: https://codepen.io/flux-knot/pen/jyxNKz
*/}

export default function Home() {
  {/** 
    - text white is master styling
    - the color of the bg should be height of the screen 
    - make parent snap mandatory and height screen
    - your child will be snapping*/}
  return (
    <div className='bg-[rgb(15,15,15)] text-white h-screen snap-y snap-mandatory overflow-scroll z-0'>
      <Head>
        <title>Irwan's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      {/* Hero 
        * Section is SEO friendly
        * make it snap center*/}
      {/* <section id="hero" className='snap-start'> */}
      <section id="hero" className='snap-start'>
        <Hero />
      </section>

      <section id="about" className='snap-center'>
        <About/>
      </section>
      
      <section id="experience" className='snap-center'>
        <WorkExperience />
      </section>

      {/* Skills */}
      <section id="skills" className='snap-start'>
        <Skills />
      </section>

      {/* Projects */}
      <section id="project" className='snap-start'>
        <Projects />
      </section>

      {/* Contact Me */}
    </div>
  )
}